version: '3.9'
services:
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: hl
      MYSQL_USER: hl
      MYSQL_PASSWORD: hl
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
      - ./backend/migrations:/migrations

  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8081:8080